"""Types for the extension module. Its documentation is in src/lib.rs."""

from collections.abc import Awaitable, Iterable, Mapping
from typing import Any, Literal, TypeAlias

__version__: str
DEFAULT_MODEL: str
DECISIONS_URL: str
DEFAULT_TIMEOUT: float

#: Any JSON value: a state, instructions and criteria are usually strings, but needn't be.
Json: TypeAlias = Any
Questions: TypeAlias = Mapping[str, Question | Mapping[str, Json]] | Iterable[tuple[str, Question | Mapping[str, Json]]]
Answer: TypeAlias = ChoiceAnswer | ScoreAnswer | NoulAnswer | dict[str, Json]

class JevError(Exception): ...
class HttpError(JevError): ...

class StatusError(JevError):
    status: int

class DecodeError(JevError): ...
class InvalidQuestionError(JevError): ...
class MissingAnswerError(JevError): ...
class WrongTypeError(JevError): ...
class BadAnswerError(JevError): ...
class NumericalError(JevError): ...
class RulesError(JevError): ...

class Question:
    @staticmethod
    def choice(instructions: Json, options: Mapping[str, Json] | Iterable[str | tuple[str, Json]]) -> Question: ...
    @staticmethod
    def score(instructions: Json, levels: Iterable[Json]) -> Question: ...
    @staticmethod
    def noul(instructions: Json, yes: Json | None = None, no: Json | None = None) -> Question: ...
    @staticmethod
    def from_dict(question: Mapping[str, Json]) -> Question: ...
    @property
    def kind(self) -> Literal["choice", "score", "noul"]: ...
    @property
    def instructions(self) -> Json: ...
    def to_dict(self) -> dict[str, Json]: ...
    def check(self) -> None: ...

def load_questions(text: str) -> dict[str, Question]: ...

class Client:
    def __init__(
        self, key: str | None = None, *, model: str | None = None, url: str | None = None, timeout: float | None = None
    ) -> None: ...
    @property
    def model(self) -> str: ...
    @property
    def url(self) -> str: ...
    def request(self, state: Json, questions: Questions) -> dict[str, Json]: ...
    def decide(self, state: Json, questions: Questions) -> DecisionResponse: ...
    def decide_async(self, state: Json, questions: Questions) -> Awaitable[DecisionResponse]: ...

class Usage:
    @property
    def input_tokens(self) -> int: ...
    @property
    def output_tokens(self) -> int: ...
    @property
    def cost(self) -> float | None: ...

class ChoiceAnswer:
    @property
    def kind(self) -> Literal["choice"]: ...
    @property
    def choice(self) -> str: ...
    @property
    def confidence(self) -> float: ...
    @property
    def probabilities(self) -> dict[str, float]: ...

class ScoreAnswer:
    @property
    def kind(self) -> Literal["score"]: ...
    @property
    def score(self) -> float: ...
    @property
    def confidence(self) -> float: ...
    @property
    def probabilities(self) -> dict[int, float]: ...
    @property
    def legend(self) -> dict[int, Json]: ...

class NoulAnswer:
    @property
    def kind(self) -> Literal["noul"]: ...
    @property
    def noul(self) -> float: ...
    def __float__(self) -> float: ...

class DecisionResponse:
    @staticmethod
    def from_json(text: str) -> DecisionResponse: ...
    @staticmethod
    def from_dict(reply: Mapping[str, Json]) -> DecisionResponse: ...
    @property
    def model(self) -> str: ...
    @property
    def id(self) -> str | None: ...
    @property
    def provider(self) -> str | None: ...
    @property
    def usage(self) -> Usage: ...
    @property
    def answers(self) -> dict[str, Answer]: ...
    def answer(self, id: str) -> Answer: ...
    def choice(self, id: str) -> ChoiceAnswer: ...
    def score(self, id: str) -> ScoreAnswer: ...
    def noul(self, id: str) -> float: ...
    def to_dict(self) -> dict[str, Json]: ...
    def to_json(self, indent: bool = False) -> str: ...
    def render(self, format: Literal["text", "table", "json"] = "text", ids: list[str] | None = None, width: int = 100) -> str: ...
    def __getitem__(self, id: str) -> Answer: ...
    def __contains__(self, id: str) -> bool: ...
    def __len__(self) -> int: ...

class Rules:
    def __init__(self, text: str, questions: Questions) -> None: ...
    def evaluate(self, reply: DecisionResponse) -> Outcome: ...
    def graph_text(self, reply: DecisionResponse | None = None) -> str: ...
    def graph_svg(self, reply: DecisionResponse | None = None) -> str: ...

class Item:
    @property
    def name(self) -> str: ...
    @property
    def score(self) -> float: ...
    @property
    def yes(self) -> bool: ...
    @property
    def rules(self) -> list[dict[str, Json]]: ...
    def __bool__(self) -> bool: ...

class OutputValue:
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> float | None: ...
    @property
    def sets(self) -> list[tuple[str, float]]: ...
    @property
    def rules(self) -> dict[str, list[dict[str, Json]]]: ...

class Outcome:
    @property
    def threshold(self) -> float: ...
    @property
    def items(self) -> list[Item]: ...
    @property
    def outputs(self) -> list[OutputValue]: ...
    @property
    def yes(self) -> list[str]: ...
    def __getitem__(self, name: str) -> Item | OutputValue: ...
    def text(self) -> str: ...
    def to_dict(self) -> dict[str, Json]: ...
